# Generated by Django 5.2 on 2025-04-28 00:52

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена в ')),
                ('tx_ref', models.CharField(max_length=100, null=True, unique=True, verbose_name='Уникальный код')),
                ('delivery_status', models.CharField(choices=[('PENDING', 'PENDING'), ('PACKING', 'PACKING'), ('SHIPPING', 'SHIPPING'), ('ARRIVING', 'ARRIVING'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=8, verbose_name='Статус доставки')),
                ('payment_status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('CANCELED', 'CANCELED'), ('FAILED', 'FAILED')], default='PENDING', max_length=10, verbose_name='Статус оплаты')),
                ('date_delivered', models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки')),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='BY')),
                ('address', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('zipcode', models.CharField(max_length=6, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена в ')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='profiles.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена в ')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BY', verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('city', models.CharField(max_length=200, verbose_name='Город доставки')),
                ('country', models.CharField(max_length=200, verbose_name='Страна доставки')),
                ('zipcode', models.CharField(max_length=6, verbose_name='Почтовый индекс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
