# Generated by Django 5.2 on 2025-04-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PACKING', 'PACKING'), ('SHIPPING', 'SHIPPING'), ('ARRIVING', 'ARRIVING'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=8, verbose_name='Статус доставки'),
        ),
    ]
