name: shop_drf
services:
  db:
    image: postgres:16.8
    env_file: .env
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${SQL_DATABASE} -U ${SQL_USER}"]
      interval: 5s
      timeout: 3s
      retries: 3
volumes:
  postgres-data:


