# Generated by Django 5.2 on 2025-04-28 00:52

import autoslug.fields
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена в ')),
                ('business_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='business_name', verbose_name='SLUG')),
                ('inn_identification_number', models.CharField(max_length=12, verbose_name='ИНН')),
                ('website_url', models.URLField(null=True, verbose_name='URL-адрес сайта бизнеса ')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BY', verbose_name='Номер телефона')),
                ('business_description', models.TextField(null=True, verbose_name='Описание бизнеса')),
                ('business_address', models.CharField(max_length=255, verbose_name='Адрес бизнеса')),
                ('city', models.CharField(max_length=100, verbose_name='Город нахождения')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Почтовый индекс')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Название банка')),
                ('bank_bic_number', models.CharField(max_length=9, verbose_name='BIC')),
                ('bank_account_number', models.CharField(max_length=28, verbose_name='IBAN')),
                ('bank_routing_number', models.CharField(max_length=20, verbose_name='Номер банковского счета ')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Проверен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
