# Generated by Django 5.2 on 2025-05-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL-адрес сайта бизнеса'),
        ),
    ]
